"""Turns src/web/*.html into a C++ header of PROGMEM string literals.

The web UI used to live inside WebConfigServer.cpp as one 17 KB raw string
literal, where no editor would treat it as HTML: no highlighting, no tag
matching, no formatter, and every edit showed up in the diff of a C++ file.
Keeping it as a real .html file costs one generated header, produced before
each build so the two can never drift.

The generated header is not checked in. src/web/ is the source of truth.
"""
import os

Import("env")  # noqa: F821 - injected by PlatformIO

WEB_DIR = os.path.join(env.subst("$PROJECT_SRC_DIR"), "web")  # noqa: F821
OUT_DIR = os.path.join(env.subst("$PROJECT_SRC_DIR"), "generated")  # noqa: F821
OUT_FILE = os.path.join(OUT_DIR, "WebUiHtml.h")

# A raw literal ends at the delimiter, so the delimiter must not be able to
# appear in the HTML. Checked below rather than assumed.
DELIM = "WEBUI"


def symbol_for(filename):
    stem = os.path.splitext(filename)[0]
    return "k" + "".join(part.capitalize() for part in stem.split("_")) + "Html"


def generate():
    if not os.path.isdir(WEB_DIR):
        return
    sources = sorted(f for f in os.listdir(WEB_DIR) if f.endswith(".html"))
    if not sources:
        return

    parts = [
        "// Generated by scripts/embed_web.py from src/web/. Do not edit:",
        "// change the .html file instead, the next build overwrites this.",
        "#pragma once",
        "",
        "#include <Arduino.h>",
        "",
    ]
    for name in sources:
        with open(os.path.join(WEB_DIR, name), encoding="utf-8") as handle:
            html = handle.read()
        closing = ")" + DELIM + '"'
        if closing in html:
            raise ValueError(
                "%s contains %s, which would end the raw literal early; "
                "change DELIM in scripts/embed_web.py" % (name, closing)
            )
        parts.append(
            'const char %s[] PROGMEM = R"%s(\n%s)%s";\n'
            % (symbol_for(name), DELIM, html, DELIM)
        )

    generated = "\n".join(parts)
    # Only write when it changed, so an untouched .html does not force a
    # rebuild of everything that includes the header.
    if os.path.exists(OUT_FILE):
        with open(OUT_FILE, encoding="utf-8") as handle:
            if handle.read() == generated:
                return
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(OUT_FILE, "w", encoding="utf-8") as handle:
        handle.write(generated)
    print("embed_web: generated %s from %d file(s)" % (OUT_FILE, len(sources)))


generate()
